### ISSUE TITLE
Questions about the reimplement of baselines

### ISSUE THREAD

**Issue by Hongbin98** [Codeontheway/ISFDA-master#2]
This is good research that inspires me.
I notice that you reproduce COAL on the VisDA-C (RSUT) dataset with official codes. However, I cannot find any implementation of this baseline. Would you share this code with me? 
Looking forward to your reply!

**Comment by LeoXinhaoLee** [comment]
Hi there, thank you for your interest in our work! The code of the COAL paper was acquired through email correspondence with its original primary author. Though I may not be able to directly give this code to you without their agreement, I believe they will be happy to share their code upon your emailing them.
