### ISSUE TITLE
Label inconsistency of office-home-RSUT

### ISSUE THREAD

**Issue by yuyuliu11037** [Codeontheway/ISFDA-master#3]
Hi, thanks for your great work.

I wonder why the labels of images in data/office-home-RSUT/Clipart.txt are not consistent with data/office-home-RSUT/Clipart_UT.txt.

**Comment by LeoXinhaoLee** [comment]
Hi there, thanks for your interest in this work. 

The office-home-RSUT data split was provided by the author of the COAL paper (https://arxiv.org/abs/1910.10320). The label space of Clipart_UT and Clipart_RS are consistent, which are used as source and target domain respectively.

**Comment by yuyuliu11037** [comment]
Thank you for your reply. Yes, the label space of Clipart_UT and Clipart_RS are consistent, but not with Clipart.txt (and the problem also exists for Products and RealWord). But, anyway, it's not a big problem and I fixed it using labels in OfficeHome :)
